development:
  adapter: postgresql
  encoding: utf-8
  database: pierog_dev
  host: localhost
  pool: 64
  timeout: 5000
  username: yourusername
  password: yourpassword

test:
  adapter: postgresql
  encoding: utf-8
  database: pierog_test
  host: localhost
  pool: 64
  timeout: 5000
  username: yourusername
  password: yourpassword

production:
  adapter: postgresql
  encoding: utf-8
  database: pierog_prod
  host: localhost
  pool: 64
  timeout: 5000
  username: yourusername
  password: yourpassword
