development:
  adapter: postgresql
  encoding: utf-8
  database: pierog_dev
  host: localhost
  pool: 64
  timeout: 5000
  username: blogtest
  password: szczutkowo

test:
  adapter: postgresql
  encoding: utf-8
  database: pierog_test
  host: localhost
  pool: 64
  timeout: 5000
  username: blogtest
  password: szczutkowo

production:
  adapter: postgresql
  encoding: utf-8
  database: pierog_prod
  host: localhost
  pool: 64
  timeout: 5000
  username: blogtest
  password: szczutkowo